export const testData = {
  author: {
    name: "سیدمحمدرضا موسوی‌نژاد",
    title: "پژوهشگر جنگ، مدرس و نویسنده",
    bio: `پژوهشگر جنگ، مدرس و نویسنده ۲۳ جلد کتاب در ادبیات پایداری مقدس و جنگ، راوی فتح دفاع مقدس و مسئول ثبت و ضبط وقایع جنگ در دوران ۸ سال دفاع مقدس. رزمنده با ۵۲ ماه حضور داوطلبانه در مناطق عملیاتی و جانباز و مجروح جنگی. دارای تحصیلات آکادمی در رشته شیمی معدنی، با پایان‌نامه و رساله در خصوص لیگاندهای دو سر داندانه اسید و باز‌های نرم و سخت از دانشگاه ارومیه.`,
    contact: {
      phone: "09146543959",
      email: "musavinegahd@gmail.com",
      address: "مراغه",
    },
    social: {
      instagram: "https://instagram.com/mousavinejad",
      twitter: "https://twitter.com/mousavinejad",
    },
  },
  books: [
    {
      id: 1,
      title: "اسطوره‌های تاریخ مقاومت ایران - جلد اول",
      description: "بررسی تاریخ مقاومت و ایثار ملت ایران در دفاع مقدس",
      shortDescription: "جلد اول از مجموعه پنج جلدی اسطوره‌های تاریخ مقاومت",
      image: "/images/book4.jpg",
      publishDate: "۱۳۹۸",
      price: "۱۲۰,۰۰۰ تومان",
    },
    {
      id: 2,
      title: "یادهای نیک - جلد اول",
      description: "روایتی از خاطرات رزمندگان دفاع مقدس",
      shortDescription: "جلد اول از مجموعه سه جلدی یادهای نیک",
      image: "/images/book1.jpg",
      publishDate: "۱۳۹۹",
      price: "۹۸,۰۰۰ تومان",
    },
    {
      id: 3,
      title: "عمری که مرا داده شده - جلد سوم",
      description: "بر زمین چنین گذشت",
      shortDescription: "روایتی از زندگی و خاطرات جنگ",
      image: "/images/book2.jpg",
      publishDate: "۱۴۰۰",
      price: "۸۵,۰۰۰ تومان",
    },
    {
      id: 4,
      title: "اسطوره‌های تاریخ مقاومت ایران - جلد دوم",
      description: "ادامه روایت تاریخ مقاومت و ایثار ملت ایران",
      shortDescription: "جلد دوم از مجموعه پنج جلدی اسطوره‌های تاریخ مقاومت",
      image: "/images/book3.jpg",
      publishDate: "۱۴۰۱",
      price: "۱۱۰,۰۰۰ تومان",
    },
  ],
  speeches: [
    {
      id: 1,
      title: "روایتگری دفاع مقدس",
      date: "۱۵ مهر ۱۴۰۲",
      location: "دانشگاه تهران",
      description: "روایتگری و بررسی وقایع دفاع مقدس با حضور رزمندگان",
    },
    {
      id: 2,
      title: "نشست تخصصی ادبیات پایداری",
      date: "۲۰ آبان ۱۴۰۲",
      location: "فرهنگسرای انقلاب",
      description: "بررسی جایگاه ادبیات پایداری در تاریخ معاصر ایران",
    },
  ],
  latestNews: {
    title: "انتشار کتاب جدید",
    description: "جلد پنجم کتاب اسطوره‌های تاریخ مقاومت ایران منتشر شد",
    image: "/images/banner1.jpg",
    link: "/books/1",
  },
};
